/*
TodoList API

This is a sample server for a todo list.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelsTodo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsTodo{}

// ModelsTodo struct for ModelsTodo
type ModelsTodo struct {
	Done *bool `json:"done,omitempty"`
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewModelsTodo instantiates a new ModelsTodo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsTodo() *ModelsTodo {
	this := ModelsTodo{}
	return &this
}

// NewModelsTodoWithDefaults instantiates a new ModelsTodo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsTodoWithDefaults() *ModelsTodo {
	this := ModelsTodo{}
	return &this
}

// GetDone returns the Done field value if set, zero value otherwise.
func (o *ModelsTodo) GetDone() bool {
	if o == nil || IsNil(o.Done) {
		var ret bool
		return ret
	}
	return *o.Done
}

// GetDoneOk returns a tuple with the Done field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTodo) GetDoneOk() (*bool, bool) {
	if o == nil || IsNil(o.Done) {
		return nil, false
	}
	return o.Done, true
}

// HasDone returns a boolean if a field has been set.
func (o *ModelsTodo) HasDone() bool {
	if o != nil && !IsNil(o.Done) {
		return true
	}

	return false
}

// SetDone gets a reference to the given bool and assigns it to the Done field.
func (o *ModelsTodo) SetDone(v bool) {
	o.Done = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsTodo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTodo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsTodo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsTodo) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ModelsTodo) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsTodo) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ModelsTodo) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ModelsTodo) SetTitle(v string) {
	o.Title = &v
}

func (o ModelsTodo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsTodo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Done) {
		toSerialize["done"] = o.Done
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableModelsTodo struct {
	value *ModelsTodo
	isSet bool
}

func (v NullableModelsTodo) Get() *ModelsTodo {
	return v.value
}

func (v *NullableModelsTodo) Set(val *ModelsTodo) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsTodo) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsTodo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsTodo(val *ModelsTodo) *NullableModelsTodo {
	return &NullableModelsTodo{value: val, isSet: true}
}

func (v NullableModelsTodo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsTodo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


